#!/usr/bin/env bash
# script to configure subdomains and display information about them.

domain=$1
subdomain=$2

declare -A subdomains
subdomains=(
    ["www"]="lb-01-IP"
    ["lb-01"]="lb-01-IP"
    ["web-01"]="web-01-IP"
    ["web-02"]="web-02-IP"
)

get_dns_record() {
    local sub=$1
    local fqdn="$sub.$domain"
    local record_info=$(dig +short $fqdn)
    
    if [[ -n "$record_info" ]]; then
        echo "The subdomain $sub is a A record and points to $record_info"
    else
        echo "No DNS record found for $fqdn"
    fi
}

if [[ -z "$domain" ]]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

if [[ -n "$subdomain" ]]; then
    get_dns_record "$subdomain"
else
    for sub in "www" "lb-01" "web-01" "web-02"; do
        get_dns_record "$sub"
    done
fi
